version: '3.7'

services:

  picasso:
    build: 
      context: .
      args:
        environment: dev
    depends_on:
      - picasso-wp-db
    environment:
      - 'environment=local'
      - 'PICASSO_DB_NAME=picasso_wp_${APP_LOCATION}'
      - 'PICASSO_DB_HOST=${PICASSO_DB_HOST}'
      - 'PICASSO_DB_USER=${PICASSO_DB_USER}'
      - 'PICASSO_DB_PASSWORD=${PICASSO_DB_PASSWORD}'
    networks:
      - default
      - lighthouse
    ports:
      - '${LOCAL_PICASSO_PORT}:80'
    volumes:
      - ./html:/var/www/html:cached

  wp-cli:
    image: wordpress:cli-2.4.0-php7.3
    env_file: .env
    working_dir: /var/www/html
    environment:
      - 'PICASSO_DB_NAME=picasso_wp_${APP_LOCATION}'
      - 'PICASSO_DB_HOST=${PICASSO_DB_HOST}'
      - 'PICASSO_DB_USER=${PICASSO_DB_USER}'
      - 'PICASSO_DB_PASSWORD=${PICASSO_DB_PASSWORD}'
    volumes:
      - ./html:/var/www/html:cached

  picasso-wp-db:
    image: mysql:5.7
    env_file: .env
    environment:
      - 'MYSQL_DATABASE=picasso_wp_${APP_LOCATION}'
      - 'MYSQL_USER=${PICASSO_DB_USER}'
      - 'MYSQL_PASSWORD=${PICASSO_DB_PASSWORD}'
      - 'MYSQL_RANDOM_ROOT_PASSWORD=1'
    volumes:
      - ./db:/var/lib/mysql:delegated

networks:
  lighthouse:
    external:
      name: apfm-lighthouse