version: '3.7'

services:
  picasso:
    image: wordpress:5.3.2-php7.3
    env_file: .env
    working_dir: /var/www/html
    environment:
      - 'PICASSO_DB_NAME=picasso_wp_${APP_LOCATION}'
      - 'PICASSO_DB_HOST=${PICASSO_DB_HOST}'
      - 'PICASSO_DB_USER=${PICASSO_DB_USER}'
      - 'PICASSO_DB_PASSWORD=${PICASSO_DB_PASSWORD}'
    volumes:
      - ./html:/var/www/html:cached
    ports:
      - '${LOCAL_PICASSO_PORT}:80'
    networks:
      - default
      - lighthouse

networks:
  lighthouse:
    external:
      name: apfm-lighthouse
